---

- name: OpenHPC - skip installing documentation on compute nodes
  lineinfile:
    create: yes
    path: "{{ ansible_env.HOME }}/.rpmmacros"
    line: '%_excludedocs 1'

- name: OpenHPC - install ohpc-base-compute via Yum
  yum:
    name: ohpc-base-compute
    state: present

- name: OpenHPC - install modules user environment via Yum
  yum:
    name: lmod-ohpc
    state: present

